### ISSUE TITLE
fuzzy bank search: plugin now hides a large portion of the bank

### ISSUE THREAD

**Issue by Felanbird** [i/rl-plugins#3]
Reported a couple times in the Runelite discord, likely caused by the bank-overlay overhaul, I believe this compare should cover the changes. https://github.com/runelite/runelite/compare/2c79c0b400c97c8aafcfc5fdb92816a090c7ecdb...d961daf48848a679d55fcf708c3b67daffc1f235

If you have any questions about fixing it you can ask in the [Runelite discord](https://runelite.net/discord)

**Comment by i** [comment]
fixed
